# a very minimal declarative config file
_format_version: "2.1"
_transform: true

services:
  - name: proxy-service
    url: http://host.docker.internal:8005
    routes:
      - name: all-routes
        paths:
          - /api
  - name: login-service
    url: http://host.docker.internal:8005/login
    routes:
      - name: login-route
        paths:
          - /login
